// Root-level middleware file that re-exports from src/middleware.ts
// This is needed for Next.js standalone builds to properly detect the middleware
// DO NOT EDIT THIS FILE - Edit src/middleware.ts instead

export { default, config } from './src/middleware'