/**
 * Get Insight Tool - Category 3 Domain Intelligence
 *
 * Retrieves detailed information about a specific Action Center insight.
 * Used when users click "Ask AI" on an insight card and want to investigate.
 *
 * The insight already contains server-side analysis (Z-scores, risk factors, etc.)
 * from when it was generated by the proactive detection system.
 */

import { BaseTool, UserContext, ToolParameters, ToolResult, OpenAIToolSchema, ModelType } from './base-tool'

export class GetInsightTool extends BaseTool {
  getToolName(modelType?: ModelType): string {
    return 'get_action_center_insight'
  }

  getDescription(modelType?: ModelType): string {
    return `Retrieve detailed information about a specific Action Center insight by ID.
Returns the full insight including category, priority, description, affected entities, and metadata.
Use this when investigating a specific alert from the Action Center.
The insight ID is provided when users click "Ask AI" on an insight card.`
  }

  getToolSchema(modelType?: ModelType): OpenAIToolSchema {
    return {
      type: "function",
      function: {
        name: this.getToolName(modelType),
        description: this.getDescription(modelType),
        parameters: {
          type: "object",
          properties: {
            insight_id: {
              type: "string",
              description: "The unique identifier of the Action Center insight to retrieve"
            }
          },
          required: ["insight_id"]
        }
      }
    }
  }

  protected async validateParameters(parameters: ToolParameters): Promise<{ valid: boolean; error?: string }> {
    if (!parameters.insight_id || typeof parameters.insight_id !== 'string') {
      return { valid: false, error: 'insight_id is required and must be a string' }
    }
    return { valid: true }
  }

  protected async executeInternal(parameters: ToolParameters, userContext: UserContext): Promise<ToolResult> {
    if (!this.convex || !userContext.businessId) {
      return {
        success: false,
        error: 'Missing authenticated Convex client or business context'
      }
    }

    try {
      console.log(`[GetInsightTool] Looking up insight ${parameters.insight_id}`)

      // Call the Action Center insights query
      // Note: insightId is typed as v.id("actionCenterInsights") in Convex
      const insight = await this.convex.query(
        this.convexApi.functions.actionCenterInsights.getById,
        {
          insightId: parameters.insight_id as any, // Cast to any since we're passing a string that represents the ID
        }
      )

      if (!insight) {
        return {
          success: false,
          error: `Insight not found with ID: ${parameters.insight_id}`
        }
      }

      console.log(`[GetInsightTool] Found insight: ${insight.title} (${insight.category}/${insight.priority})`)

      return {
        success: true,
        data: {
          id: insight._id,
          title: insight.title,
          description: insight.description,
          category: insight.category,
          priority: insight.priority,
          status: insight.status,
          recommendedAction: insight.recommendedAction,
          affectedEntities: insight.affectedEntities,
          detectedAt: new Date(insight.detectedAt).toISOString(),
          metadata: insight.metadata,
        },
        metadata: {
          insightId: insight._id.toString(),
          category: insight.category,
          priority: insight.priority,
        }
      }
    } catch (error) {
      console.error('[GetInsightTool] Error:', error)
      return {
        success: false,
        error: `Failed to retrieve insight: ${error instanceof Error ? error.message : 'Unknown error'}`
      }
    }
  }

  protected formatResultData(data: any[]): string {
    return ''
  }
}
