/**
 * Get Insight Tool - Category 3 Domain Intelligence
 *
 * Retrieves detailed information about a specific Action Center insight.
 * Used when users click "Ask AI" on an insight card and want to investigate.
 *
 * The insight already contains server-side analysis (Z-scores, risk factors, etc.)
 * from when it was generated by the proactive detection system.
 */

import { BaseTool, UserContext, ToolParameters, ToolResult, OpenAIToolSchema, ModelType } from './base-tool'
import { callMCPToolFromAgent } from './mcp-tool-wrapper'

export class GetInsightTool extends BaseTool {
  getToolName(modelType?: ModelType): string {
    return 'get_action_center_insight'
  }

  getDescription(modelType?: ModelType): string {
    return `Retrieve detailed information about a specific Action Center insight by ID.
Returns the full insight including category, priority, description, affected entities, and metadata.
Use this when investigating a specific alert from the Action Center.
The insight ID is provided when users click "Ask AI" on an insight card.`
  }

  getToolSchema(modelType?: ModelType): OpenAIToolSchema {
    return {
      type: "function",
      function: {
        name: this.getToolName(modelType),
        description: this.getDescription(modelType),
        parameters: {
          type: "object",
          properties: {
            insight_id: {
              type: "string",
              description: "The unique identifier of the Action Center insight to retrieve"
            }
          },
          required: ["insight_id"]
        }
      }
    }
  }

  protected async validateParameters(parameters: ToolParameters): Promise<{ valid: boolean; error?: string }> {
    if (!parameters.insight_id || typeof parameters.insight_id !== 'string') {
      return { valid: false, error: 'insight_id is required and must be a string' }
    }
    return { valid: true }
  }

  protected async executeInternal(parameters: ToolParameters, userContext: UserContext): Promise<ToolResult> {
    // 032-mcp-first: Delegate to MCP server (single source of truth)
    return callMCPToolFromAgent('get_action_center_insight', {
      insight_id: parameters.insight_id,
    }, userContext)
  }

  protected formatResultData(data: any[]): string {
    return ''
  }
}
